2019/11/26 16:46:17 [error] 6#6: *908 open() "/WWW/static/assets/css/ajax-loader.gif" failed (2: No such file or directory), client: 172.18.0.1, server: hello_django.local, request: "GET /static/assets/css/ajax-loader.gif HTTP/1.1", host: "localhost", referrer: "https://localhost/"
2019/11/26 16:46:17 [error] 6#6: *910 open() "/WWW/static/assets/css/fonts/slick.woff" failed (2: No such file or directory), client: 172.18.0.1, server: hello_django.local, request: "GET /static/assets/css/fonts/slick.woff HTTP/1.1", host: "localhost", referrer: "https://localhost/"
2019/11/26 16:46:17 [error] 6#6: *908 open() "/WWW/static/assets/css/fonts/slick.ttf" failed (2: No such file or directory), client: 172.18.0.1, server: hello_django.local, request: "GET /static/assets/css/fonts/slick.ttf HTTP/1.1", host: "localhost", referrer: "https://localhost/"
2019/11/26 16:46:17 [error] 6#6: *908 open() "/WWW/static/assets/css/fonts/slick.svg" failed (2: No such file or directory), client: 172.18.0.1, server: hello_django.local, request: "GET /static/assets/css/fonts/slick.svg HTTP/1.1", host: "localhost", referrer: "https://localhost/"
2019/12/28 05:29:35 [error] 6#6: *34 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.18.0.1, server: hello_django.local, request: "GET / HTTP/1.1", upstream: "http://172.18.0.4:8000/", host: "localhost"
2019/12/28 05:29:38 [error] 6#6: *34 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.18.0.1, server: hello_django.local, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.18.0.4:8000/favicon.ico", host: "localhost", referrer: "https://localhost/"
2019/12/28 05:37:31 [error] 6#6: *39 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.18.0.1, server: hello_django.local, request: "GET / HTTP/1.1", upstream: "http://172.18.0.4:8000/", host: "localhost"
2019/12/28 05:37:36 [error] 6#6: *39 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.18.0.1, server: hello_django.local, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.18.0.4:8000/favicon.ico", host: "localhost", referrer: "https://localhost/"
2019/12/28 05:41:06 [error] 6#6: *44 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: hello_django.local, request: "GET / HTTP/1.1", upstream: "http://172.18.0.4:8000/", host: "localhost"
2019/12/28 05:41:06 [error] 6#6: *44 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: hello_django.local, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.18.0.4:8000/favicon.ico", host: "localhost", referrer: "https://localhost/"
2019/12/28 05:43:09 [error] 6#6: *49 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: hello_django.local, request: "GET / HTTP/1.1", upstream: "http://172.18.0.4:8000/", host: "localhost"
2019/12/28 05:43:09 [error] 6#6: *49 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: hello_django.local, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.18.0.4:8000/favicon.ico", host: "localhost", referrer: "https://localhost/"
